name: Moonshot
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-moonshot:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        os: ['self-hosted']
        arch: ['x64']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup NVIDIA compilers
        run: |
          module load nvhpc
          echo "$(dirname $(which nvcc))" >> $GITHUB_PATH

      - name: Configure SPRAL
        run: |
          rm -rf builddir
          FC=gfortran CC=gcc CXX=g++ /home/amontoison/.local/bin/meson setup builddir --buildtype=debug

      - name: Compile SPRAL
        run: /home/amontoison/.local/bin/meson compile -C builddir

      - name: Test SPRAL
        run: /home/amontoison/.local/bin/meson test -C builddir
