name: 'Mac Tests'

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  linux-tests:
    strategy:
      matrix:
        gcc_ver: [11]
    name: 'MacOS (gcc-${{ matrix.gcc_ver }})'
    runs-on: macos-latest
    env:
      # Set environ for OpenMP
      OMP_NESTED: true
      OMP_CANCELLATION: true
      OMP_PROC_BIND: true
      OMP_NUM_THREADS: 4
    steps:
      - name: 'Install dependencies'
        run: |
          brew install automake hwloc metis openblas
      - name: 'Checkout code'
        uses: actions/checkout@v2
      - name: 'Build'
        run: |
          ./autogen.sh
          ./configure CC=gcc-${{ matrix.gcc_ver }} \
                      CXX=g++-${{ matrix.gcc_ver }} \
                      F77=gfortran-${{ matrix.gcc_ver }} \
                      FC=gfortran-${{ matrix.gcc_ver }} \
                      CFLAGS="-g -O2 -Wall -I$(brew --prefix openblas)/include" \
                      CXXFLAGS="-g -O2 -Wall -I$(brew --prefix openblas)/include" \
                      FCFLAGS="-g -O2 -Wall -pedantic" \
                      LIBS="-L$(brew --prefix openblas)/lib -lopenblas" \
                      --with-metis="-L$(brew --prefix metis)/lib -lmetis"
          make
      - name: 'Test'
        run: |
          make check

